name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t react-native-community/react-native .
          docker run --rm --name rn-env react-native-community/react-native /bin/sh -c "npx envinfo"
      - name: Checkout React Native
        run: git clone https://github.com/facebook/react-native.git
      - name: Build React Native
        run: |
          docker run --rm --ulimit nofile=10240 -v "$(pwd)/scripts/":/scripts -v "$(pwd)/react-native/":/react-native -w /react-native react-native-community/react-native /bin/sh -c "/scripts/test-react-native-setup.sh"

  build-fantom:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t react-native-community/react-native .
          docker run --rm --name rn-env react-native-community/react-native /bin/sh -c "npx envinfo"
      - name: Checkout React Native
        run: git clone https://github.com/facebook/react-native.git
      - name: Create reports directory
        run: mkdir -p $(pwd)/fantom-reports
      - name: Run Fantom tests
        continue-on-error: true
        run: |
          docker run --rm --ulimit nofile=10240 -v "$(pwd)/scripts/":/scripts -v "$(pwd)/react-native/":/react-native -v "$(pwd)/fantom-reports/":/react-native/private/react-native-fantom/build/reports -w /react-native react-native-community/react-native /bin/sh -c "/scripts/test-react-native-fantom.sh"
      - name: Upload Fantom build reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: fantom-build-reports
          path: fantom-reports/
          retention-days: 30
